[versions]
kotlin = "1.9.22"
xmlunit = "2.9.1"
gradle = "8.0.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versions = "com.github.ben-manes.versions:0.47.0"
gradle-pluginPublish = "com.gradle.plugin-publish:1.2.1"
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.7.1"
jetbrains-dokka = "org.jetbrains.dokka:1.8.20"
jetbrains-changelog = "org.jetbrains.changelog:2.2.0"

[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:8.0.2"
kotlin-multiplatformPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
apache-commonsCsv = "org.apache.commons:commons-csv:1.10.0"
maven-model = "org.apache.maven:maven-model:3.9.4"
maven-artifact = "org.apache.maven:maven-artifact:3.9.4"
jUnit = "org.junit.jupiter:junit-jupiter:5.10.1"
hamcrest = "org.hamcrest:hamcrest:2.2"
ktlint = "com.pinterest:ktlint:0.49.1"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.0.0"
xmlunit-core = { module = "org.xmlunit:xmlunit-core", version.ref = "xmlunit" }
xmlunit-matchers = { module = "org.xmlunit:xmlunit-matchers", version.ref = "xmlunit" }
