[versions]
kotlin = "1.9.23"
xmlunit = "2.9.1"
gradle = "8.5"
maven = "3.9.6"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versions = "com.github.ben-manes.versions:0.51.0"
gradle-pluginPublish = "com.gradle.plugin-publish:1.2.1"
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.7.6"
jetbrains-dokka = "org.jetbrains.dokka:1.9.20"
jetbrains-changelog = "org.jetbrains.changelog:2.2.0"

[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:8.3.2"
kotlin-multiplatformPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
apache-commonsCsv = "org.apache.commons:commons-csv:1.11.0"
maven-model = { module = "org.apache.maven:maven-model", version.ref = "maven" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version.ref = "maven" }
jUnit = "org.junit.jupiter:junit-jupiter:5.10.2"
hamcrest = "org.hamcrest:hamcrest:2.2"
ktlint-cli = "com.pinterest.ktlint:ktlint-cli:1.2.1"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.3.1"
xmlunit-core = { module = "org.xmlunit:xmlunit-core", version.ref = "xmlunit" }
xmlunit-matchers = { module = "org.xmlunit:xmlunit-matchers", version.ref = "xmlunit" }
